djangoGuide/urls.py
from django.urls.resolvers import URLPattern
from . import views
from django.urls import path

app_name = "djangoGuide"
urlpatterns = [
	path("", views.IndexView.as_view(), name="index"),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mainApp/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from mainApp import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
]

resumewebsite/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('mainApp.urls')),
    path('djangoGuide/', include('djangoGuide.urls')),
    path('admin/', admin.site.urls),
]

djangoGuide/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mainApp/models.py
from django.db import models

# Create your models here.

djangoGuide/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = "djangoGuide/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'djangoGuide/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'djangoGuide/detail.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'djangoGuide/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # Возникает проблема состояния гонки
        return HttpResponseRedirect(reverse('djangoGuide:results', args=(question.id,)))

mainApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = "mainApp/index.html"

djangoGuide/templates/djangoGuide/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<form action="{% url 'djangoGuide:vote' question.id %}" method="post">
		{% csrf_token %}
		<fieldset>
			<legend><h1>{{ question.question_text }}</h1></legend>
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			{% for choice in question.choice_set.all %}
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
				<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
			{% endfor %}
		</fieldset>
		<input type="submit" value="Vote">
		</form>
</body>
</html>

djangoGuide/templates/djangoGuide/index.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'djangoGuide/css/style.css' %}" 
</head>

<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'djangoGuide:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>

</html>

djangoGuide/templates/djangoGuide/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'djangoGuide:detail' question.id %}">Vote again?</a>

mainApp/templates/mainApp/index.html

{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta http-equiv="Content-Type" content="text/html; charset=Windows-1251">
    <meta name="viewport" content="width=device-width, inital-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="../../static/mainApp/css/cyberTheme.css" id="theme-link">
    <title>ResumeWebSite</title>
</head>

<body>
    <div class="wrapper">
        <div class="container">
            <header class="header">
                <div>
                    <img class="header__image" src="../../static/mainApp/images/cyber.gif">
                </div>
                <div class="header__points points">
                    <div class="point__cyber point _active"></div>
                    <div class="point__japan point"></div>
                    <div class="point__classic point"></div>
                </div>
            </header>
            <div class="menu">
                <div class="menu__icon">
                    <div class="menu__bar1"></div>
                    <div class="menu__bar2"></div>
                    <div class="menu__bar3"></div>
                </div>
                <div class="menu__body">
                    <ul class="menu__list">
                        <li class="menu__link"><a href="#">Home</a></li>
                        <li class="menu__link"><a href="#">About Me</a></li>
                        <li class="menu__link"><a href="#">Blog</a></li>
                        <li class="menu__link"><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
            <main class="page">
                <div class="page__columns">
                    <div class="page__column">
                        <h2>Who am I</h2>
                        <div class="page__line"></div>
                    </div>
                    <div class="page__column">
                        <h2>Hello friend</h2>
                        <div class="page__line"></div>
                    </div>
                    <div class="page__column">
                        <h2>What is posting here</h2>
                        <div class="page__line"></div>
                    </div>
                </div>
                <div class="page__about">
                    <div class="page__about_block_1">
                        <div class="page__about_me">
                            <div class="page__about_me_text">
                                <h2>About Me:</h2>
                                <p>...</p>
                            </div>
                        </div>
                    </div>
                    <div class="page__about_block_2">
                        <div class="page__icon"><img src="../../static/mainApp/images/юзуру.jpg"></div>
                        <div class="page__text">
                            <h2>Skorzi</h2>
                            <p><a href="https://github.com/Skorzi">GitHub</a></p>
                        </div>
                    </div>
                </div>
                <div class="page__blog">
                    <div class="page__blog_block"></div>
                </div>
                <div class="page__indent"></div>
            </main>
        </div>
    </div>
    <footer class="footer">
        <div class="footer__block">
            <div class="footer__text"></div>
        </div>
    </footer>

    <script type="text/javascript" src="{% static 'mainApp/js/script.js' %}"></script>
</body>

</html>